### ISSUE TITLE
Task registration via registry.register fails 

### ISSUE THREAD

**Issue by Tobi-De** [westerveltco/django-q-registry#6]
```python
from django_q.models import Schedule
from django_q_registry.registry import registry

registry.register(
    send_mail,
    name="Send periodic test email",
    next_run=timezone.now(),
    schedule_type=Schedule.MINUTES,
    minutes=5,
    kwargs={
        "subject": "Test email from reminders",
        "message": "This is a test email.",
        **base_kwargs,
    },
)
```
The issue is with the kwargs argument

```shell
  File "/home/tobi/Builds/reminders/venv/lib64/python3.12/site-packages/django_q_registry/registry.py", line 127, in _register_task
    self.registered_tasks.add(
  File "/home/tobi/Builds/reminders/venv/lib64/python3.12/site-packages/django_q_registry/registry.py", line 22, in __hash__
    return hash((self.name, self.func, tuple(self.kwargs.items())))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by Tobi-De** [comment]
I feel like I'm doing something stupid  here, sorry in advance if there is some obvious that I'm missing right now

**Comment by joshuadavidthomas** [comment]
Ah, no that looks like a legitimate bug. 

The tasks registered to a `registered_task` attribute which is a `set`. Because of that `Task` needs to be hashable, but it looks like I did a poor job implementing it (`TypeError: unhashable type: 'dict'`). What you passed in should be valid, just need to refactor the `__hash__` method on `Task` to handle `dict` and `list` data types.

Shouldn't be too hard to fix. You've already given me a great test case! 😄
