### ISSUE TITLE
Task name always include CRON

### ISSUE THREAD

**Issue by Tobi-De** [westerveltco/django-q-registry#7]
![image](https://github.com/westerveltco/django-q-registry/assets/40334729/b4430e69-1f34-4f25-879f-b5bfa6df2f88)

Regardless of the type of schedule used, the task name always includes **CRON**.

**Comment by joshuadavidthomas** [comment]
Hold over from when this was just an internal thing I copied from project to project. 

There's no *good* way to mark a scheduled task as part of the registry. The quick and easy way I came up with was to make sure the name had some identifiable string that we can filter on, so that when the `setup_periodic_tasks` management command is called the registry knows which scheduled tasks responsible for.

There has to be a better way of accomplishing this -- quick brainstorm, a model specific to this app that has a `ForeignKey` to the `Schedule` it's tied to would be a bit more robust, and keep the task name from being polluted with the extra string appended at the end.

For now, that suffix could be renamed to something a bit more generic, perhaps "- QREGISTRY" or something else.. Open to suggestions here.

In the meantime, it's actually configurable via the [`Q_REGISTRY["PERIODIC_TASK_SUFFIX"]` setting](https://github.com/westerveltco/django-q-registry/blob/2545c1a1581426790b5ae0baf283844edd640739/src/django_q_registry/conf.py#L11).

**Comment by joshuadavidthomas** [comment]
Also, Falco is super cool! I've definitely looked at in the past, but went with my own template because, you know, I've got **Opinions**. 😄

I saw that you name checked `django-twc-project`, thanks for that! 🎉 🍻

**Comment by Tobi-De** [comment]
> Also, Falco is super cool! I've definitely looked at in the past, but went with my own template because, you know, I've got **Opinions**. 😄
> 
> I saw that you name checked `django-twc-project`, thanks for that! 🎉 🍻

Understandable :smile:
`django-twc-project` really has some great ideas in it, I'm planning to steal some more :)

**Comment by Tobi-De** [comment]
> Hold over from when this was just an internal thing I copied from project to project.
> 
> There's no _good_ way to mark a scheduled task as part of the registry. The quick and easy way I came up with was to make sure the name had some identifiable string that we can filter on, so that when the `setup_periodic_tasks` management command is called the registry knows which scheduled tasks its responsible for.
> 
> There has to be a better way of accomplishing this -- quick brainstorm, a model specific to this app that has a `ForeignKey` to the `Schedule` it's tied to would be a bit more robust, and keep the task name from being polluted with the extra string appended at the end.
> 
> For now, that suffix could be renamed to something a bit more generic, perhaps "- QREGISTRY" or something else.. Open to suggestions here.
> 
> In the meantime, it's actually configurable via the [`Q_REGISTRY["PERIODIC_TASK_SUFFIX"]` setting](https://github.com/westerveltco/django-q-registry/blob/2545c1a1581426790b5ae0baf283844edd640739/src/django_q_registry/conf.py#L11).

Simple is better than complex, I think `QREGISTRY` as the default is good enough, it's simple and explicit, but you just made me realized something, If I manually create a task in the admin myself, `setup_periodic_tasks` won't drop it at the next run ? I'm I right? If that's the case, that's great news and could be a good idea to mention this in the readme
